<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>netstandard2.0;netstandard2.1</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>14.0</LangVersion>

        <Configurations>Debug;Optimized</Configurations>

        <AssemblyVersion>2.0.1.0</AssemblyVersion>
        <SignAssembly>True</SignAssembly>
        <FileVersion>$(AssemblyVersion)</FileVersion>
        <ApplicationIcon>barcode_detector.ico</ApplicationIcon>
        
        <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
        <Version>2.0.1</Version>
        <PackageIcon>barcode_detector.png</PackageIcon>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        
        <Authors>Peter Metz (pmetz@inspired.codes), Steven Lee</Authors>
        <Product>Barcode Scan Detector</Product>
        <Description>Detects very fast keyboard input sequence and fires a BarcodeScanned event</Description>
        <Copyright>Inspired Codes 2026</Copyright>
        
        <PackageLicenseExpression>MIT</PackageLicenseExpression>

        <ProduceReferenceAssembly>True</ProduceReferenceAssembly>
        <EnableNETAnalyzers>True</EnableNETAnalyzers>
        <AnalysisLevel>latest-recommended</AnalysisLevel>
        
        <!-- remove parent path from PDB symbols -->
        <AppOutputBase>$(MSBuildProjectDirectory)\</AppOutputBase>
        <PathMap>$(AppOutputBase)=InspiredCodes.BarcodeScanDetector</PathMap>
        
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)'=='Debug'">
        <DefineConstants>DEBUG;TRACE</DefineConstants>
        <DebugType>full</DebugType>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)'=='Optimized'">
        <DebugType>pdbonly</DebugType>
        <Optimize>true</Optimize>
        <DefineConstants>TRACE</DefineConstants>
    </PropertyGroup>

    <ItemGroup>
        <None Include="..\README.md">
            <Pack>True</Pack>
            <PackagePath>\</PackagePath>
        </None>
        <None Include="barcode_detector.png">
            <Pack>True</Pack>
            <PackagePath></PackagePath>
        </None>
    </ItemGroup>

</Project>
